---
title: "DataFrames"
author: "Curso de algebra lineal"
date: "8/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Frames

Desde ficheros externos

```{r}

df = read.table("../../r-basic-asier/data/bulls.dat",
                header = TRUE,
                col.names = c("breed","sale_price","shoulder","fat_free",
                              "percent_ff","frame_scale","back_fat",      "sale_height", "sale_weight"),
                sep = ""
                )
df

```

Guardar un DF


```{r}

write.table(df, ("/Users/asierbelazaortega/Developer/Estadistica/r-basic-asier/data/asierdata.tex"))

```


Construyendo data frames

```{r}

gender = c("H","M","M","H")
age = c(24, 35, 67, 18)
family = c(2,5,7,8)


df5 = data.frame(genero = gender, edad = age, familia = family, stringsAsFactors = TRUE)

row.names(df5) = c("P1", "P2", "P3", "P4")

df5

df5[2, ]

```




```{r}
str(iris)
sapply(subset(iris, select = 1:4), mean)
f = function(x){
  sqrt(sum(x^2))
  }
sapply(iris[1,4], f)

```


```{python}
import numpy as np
import pandas as pd

## Data frame
years = [year for year in range (1900, 2020)]
deads = [(y + np.random.uniform(0,100) -1850) for y in years]

df = pd.DataFrame({
    
    "years": years,
    "deads": deads
    
})
df.plot(x = "years", y = "deads")

```























