---
title: "Seccion 8 gráficos"
author: "Curso de algebra lineal"
date: "8/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Gráficos básicos de puntos

```{r primer plot}
x = c(2,6,4,9,-1)
y = c(1,8,4, -2, 4)
plot(x,y)

plot (2^(1:6))
```
Si queremos hacer una función $f()x$

```{r}

f = function(x){
  sqrt(x)
}
plot(f)
```

Modificando la visualización:

Escala logarítmica:

```{r}
par(mfrow = c(1,2))
plot = plot( exp(1:20), xlab = "Índice", ylab = expression(e^{1:20}), main = "Escala Lineal" )

plotLog = plot( exp(1:20), log = "y", xlab = "Índice", ylab = expression(e^{1:20}), main = "Escala Lineal" )
```

Parámentros


```{r}
par(mfrow = c(1,2))
n = 1:20
fib = (1/sqrt(5))*((1+sqrt(5))/2)^n - (1/sqrt(5))*((1-sqrt(5))/2)^n
plot(fib, xlab="N", ylab=expression(f[n]),
     main = "Sucesión de Fibonacci")

fib = (1/sqrt(5))*((1+sqrt(5))/2)^n - (1/sqrt(5))*((1-sqrt(5))/2)^n
plot(fib, xlab="N", ylab=expression(f[n]),
     main = "Sucesión de Fibonacci", type="h")
```


```{r}
x = (2*(1:20))
y = (-1)^(1:20)*5*(1:20)
plot (x, y, main = "Ejemplo completo", pch = 8, cex = 1, type = "b", lty = 4, lwd = 4, xaxp = c(0,40,2), yaxp = c(-100, 100, 8), bg= "blue", col="blue")
```


Más elementos:

```{r}

plot (0,0)
text(0,0, labels = "Debajo", pos = 1)
f = function(x){
  sqrt(x)
}
plot(f, xlim = c(-3, 3))
```



















































